config/routes.rb
Eliot::Application.routes.draw do
  resources :servers
  resources :reports do
    resources :metrics
  end
  root :to => 'servers#index'
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  attr_accessible :query, :report_id, :scale, :server_id

  belongs_to :server
  belongs_to :report

  def to_s
    self.query.to_s
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :description, :name, :queries

  belongs_to :server
  has_many :metrics

  def to_s
    self.name.to_s
  end
end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :base_url, :name

  has_many :reports
  has_many :metrics

  def aggregators(format=:json)
    http_get("/aggregators", format)
  end

  def logs(format=:json)
    http_get("/logs", format)
  end

  def suggest(query='', type=:metrics, format=:json)
    http_get("/suggest?q=%s&type=%s" % [query, type], format)
  end

  def version
    http_get("/version")
  end

  def query(query, start_time, end_time=Time.now.getutc)
    query_string = "/q?m=%s&start=%s&end=%s&%%s" % [ query, format_query_time(start_time), format_query_time(end_time) ]
    results = http_get(query_string % [ "json" ], :json)

    if results
      results.symbolize_keys!
      response = http_get(query_string % [ 'ascii' ], :ascii)
      results[:results] = parse_query_results(response)
    end

    results
  end

  def to_s
    self.base_url.to_s
  end

private

  def tsdb
    @tsdb ||= Faraday.new(:url => self.base_url) do |builder|
      builder.use Faraday::Request::UrlEncoded
      builder.use Faraday::Adapter::NetHttp
    end
  end

  def http_get(url, format=:plain)
    response = tsdb.get(url)

    if response.status != 200
      return nil
    end

    case format
    when :json
      JSON.parse(response.body)
    else
      response.body
    end
  end

  def format_query_time(time)
    time.getutc.strftime("%Y/%m/%d-%H:%M:%S")
  end

  def parse_query_results(response)
    results = response.scan(/^(\S+)\s+(\d{10})\s+(\d+(?:\.\d+)?)\s+(.+)$/)
    results.map do |row|
      {
        :name => row[0],
        :time => Time.at(row[1].to_i),
        :value => row[2].to_f,
        :tags => Hash[ *row[3].split(/=|\s/) ].symbolize_keys
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :html, :json

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new    
  end

  def create
    @report = Report.new(params[:report])
    @report.save
    respond_with(@report)
  end

  def update
    @report = Report.find(params[:id])
    @report.update_attributes(params[:report])
    respond_with(@report)
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    respond_with(@report)
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  respond_to :html, :except => [ :version ]
  respond_to :json, :except => [ :new, :edit, :version ]
  respond_to :text, :only => [ :version ]

  def index
    @servers = Server.all
  end

  def show
    @server = Server.find(params[:id])
  end

  def new
    @server = Server.new
  end

  def create
    @server = Server.new(params[:server])
    @server.save
    respond_with(@server)
  end

  def edit
    @server = Server.find(params[:id])
  end

  def update
    @server = Server.find(params[:id])
    @server.update_attributes(params[:server])
    respond_with(@server)
  end

  def destroy
    @server = Server.find(params[:id])
    @server.destroy
    respond_with(@server)
  end

  def version
    @server = Server.where(id: params[:id].to_i).first
    respond_to do |format|
      format.text { render :text => @server.version }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Eliot</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700" />
    <link rel="stylesheet" href="http://square.github.com/cubism/style.css" />


    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <%= link_to "Eliot", servers_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Servers", servers_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
           </div>
          </div>
        </div>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/reports/show.html.erb
<h2><%= @report.name %></h2>

<p>
<div id="ts-graph">
<div class="axis"></div>
<% Array(@report.queries).each do |query| -%>
  <div class="horizon" data-metric-query="<%= query[:query] %>" data-metric-scale="<%= query[:scale] %>">
  </div>
<% end -%>
</div>
<%= form_for [@report, @report.metrics.build], :html => { :class => 'add-metric' } do |f| -%>
  <%= f.select :server_id, options_for_select(Server.all.map{ |s| [s.name, s.id] }) %>
  <%= number_field_tag :scale, 100, :style => "width: 75px", :min => 0, :step => 10 %>
  <%= f.submit "Add metric" %>
<% end -%>
</p>

<div class="form-actions">
<%= link_to "Back", servers_path, :class => 'btn'  %>
<%= link_to "Delete", report_path(@report), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/servers/_form.html.erb
<div class="clearfix">
   <%= f.label :name, t("activerecord.attributes.server.name", :default => "Name"), :class => :label %>
  <div class="input">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :base_url, t("activerecord.attributes.server.base_url", :default => "Base url"), :class => :label %>
  <div class="input">
    <%= f.text_field :base_url, :class => 'text_field' %>
  </div>
</div>
<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", servers_path %>
</div>

app/views/servers/edit.html.erb
<%= form_for @server, :url => server_path(@server), :html => { :class => "edit_server", :id => "edit_server" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/servers/index.html.erb
<h1>Servers</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.server.name", :default => t("activerecord.labels.name", :default => "Name")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @servers.each do |server| -%>
   <tr>
    <td><%= server.id %></td>
        <td><%= link_to server.name, server_path(server) %>
    </td>
        <td><%= server.created_at %></td>
    <td>
      <%= link_to "Show", server_path(server) %>
      <%= link_to "Edit", edit_server_path(server) %>
      <%= link_to "Destroy", server_path(server), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_server_path, :class => 'btn btn-primary' %>

app/views/servers/new.html.erb
<%= form_for @server, :url => servers_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/servers/show.html.erb
<label class="label"><%= t("activerecord.attributes.server.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</label>
<p><%= @server.name %></p>

<label class="label"><%= t("activerecord.attributes.server.base_url", :default => t("activerecord.labels.base_url", :default => "Base url")) %>:</label>
<p><%= @server.base_url %></p>

<label class="label"><%= t("activerecord.attributes.server.version", :default => "Version") %>:</label>
<p><%= @server.version %></p>

<label class="label"><%= t("activerecord.attributes.server.reports", :default => "Reports") %>:</label>
<p>
<ul>
<% @server.reports.each do |report| -%>
<li><%= link_to report, server_report_path(@server, report) %></li>
<% end -%>
</ul>
<%= form_for Report.new do |f| -%>
<%= f.text_field :name, :placeholder => t("activerecord.attributes.report.name", :default => "Report Name") %>
<%= f.submit %>
<% end -%>
</p>

<div class="form-actions">
<%= link_to "Back", servers_path, :class => 'btn'  %>
<%= link_to "Edit", edit_server_path(@server), :class => 'btn' %>
<%= link_to "Delete", server_path(@server), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>